spring:
  config:
    import:
      - secret/mongo-info.yml
      - secret/front-info.yml
      - secret/slack-info.yml
  data:
    mongodb:
      uri: mongodb+srv://${mongodb.env.username}:${mongodb.env.password}@${mongodb.env.cluster}.mongodb.net/?retryWrites=true&w=majority
      database: beside
cors:
  origins: '*'
#  origins: 127.0.0.1, localhost, 223.130.136.211

---

spring:
  config:
    activate:
      on-profile: local
log:
  level: info

---

spring:
  config:
    activate:
      on-profile: release
log:
  path: /logs
  filename: beside-15th-11team
  level: warn