spring:
  config:
    import:
      - secret/mongo-info.yml
      - secret/front-info.yml
      - secret/slack-info.yml
      - secret/jwt-info.yml
      - secret/oauth-info.yml
  data:
    mongodb:
      uri: mongodb+srv://${mongodb.env.username}:${mongodb.env.password}@${mongodb.env.cluster}.mongodb.net/?retryWrites=true&w=majority
      database: beside
management:
  endpoints:
    web:
      exposure:
        include: '*'
jwt:
  baseKey: ${jwt.baseKey}
  cookie:
    name: jwt
sign:
  whitePaths: ${oauth.apple.redirectUri}, ${oauth.kakao.redirectUri}
  attributeName: jwt
oauth:
  kakao:
    accessTokenUri: https://kauth.kakao.com/oauth/token
    apiUri: https://kapi.kakao.com/v2/user/me
  apple:
    accessTokenUri: https://appleid.apple.com/auth/token

---

spring:
  config:
    activate:
      on-profile: local
cors:
  origins: *
server:
  port: 443
  ssl:
    key-store: classpath:local.p12
    key-store-type: PKCS12
    key-store-password: local
log:
  level: info

---

spring:
  config:
    activate:
      on-profile: release
    import:
      - secret/ssl-info.yml
cors:
#  origins: www.byeoljachui.com
  origins: *
server:
  port: 443
  ssl:
    key-store: classpath:beside.p12
    key-store-type: PKCS12
    key-store-password: ${ssl.password}
log:
  path: /root/logs/
  fileName: startrail
  level: warn
static:
  path: /root/static/