spring:
  data:
    mongodb:
      uri: mongodb+srv://beside15th11team:beside11!@beside.hxhx7vu.mongodb.net/?retryWrites=true&w=majority
      database: beside
static:
  path: /Users/user/beside/
cors:
  origins: '*'
#  origins: 127.0.0.1, localhost, 223.130.136.211

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: release

static:
  path: /root/static