spring:
  config:
    import:
      - secret/mongo-info.yml
      - secret/front-info.yml
      - secret/slack-info.yml
      - secret/jwt-info.yml
      - secret/oauth-info.yml
  data:
    mongodb:
      uri: mongodb+srv://${mongodb.env.username}:${mongodb.env.password}@${mongodb.env.cluster}.mongodb.net/?retryWrites=true&w=majority
      database: beside
cors:
  origins: www.byeoljachui.com
management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  baseKey: ${jwt.baseKey}
  cookie:
    name: jwt
sign:
  whitePaths: /sign, /users
  attributeName: jwt

---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
log:
  level: info
---

spring:
  config:
    activate:
      on-profile: release
    import:
      - secret/ssl-info.yml

server:
  port: 443
  ssl:
    key-store: classpath:beside.p12
    key-store-type: PKCS12
    key-store-password: ${ssl.password}
log:
  path: /root/logs/
  fileName: beside-15th-11team
  level: warn
static:
  path: /root/static/