name: deploy

on:
  push:
    branches: [temp/deploy]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Project JDK 17 Setting
      - name: Checkout
        uses: actions/checkout@v3
      - run: mkdir -p ./src/main/resources/secret
      - run: touch ./src/main/resources/secret/mongo-info.yml
      - run: echo "${{ secrets.MONGO_INFO }}" > ./src/main/resources/secret/mongo-info.yml
      - run: cat ./src/main/resources/secret/mongo-info.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      # main Branch Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: release-artifact

      - name: Deploy Release artifact using SCP
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.NCP_USERNAME }}
          host: ${{ secrets.NCP_HOST }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          source: "*.jar"
          target: "~/app/backend"
          strip_components: 2

      - name: Transfer Deploy Script use SCP
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.NCP_USERNAME }}
          host: ${{ secrets.NCP_HOST }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          source: "deploy.sh"
          target: "~/app/backend"

      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.NCP_USERNAME }}
          host: ${{ secrets.NCP_HOST }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script_stop: true
          script: chmod +x ~/app/backend && sh ~/app/backend/deploy.sh