name: deploy

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout & Secret yml create
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          mkdir -p ./src/main/resources/secret
          touch ./src/main/resources/secret/mongo-info.yml
          echo "${{ secrets.MONGO_INFO }}" > ./src/main/resources/secret/mongo-info.yml
          cat ./src/main/resources/secret/mongo-info.yml

      # Project JDK 17 setting
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      # main Branch Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # make release artifact
      - name: Add artifacts to publish to the deploy folder
        run: |
          mkdir -p ./deploy
          cp -r ./target/*.jar ./deploy
          cp -r ./deploy.sh ./deploy

      # Upload release artifact
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: ./deploy

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      # Upload release artifact
      - name: Download artifact jar
        uses: actions/download-artifact@v2
        with:
          name: release-artifact

      # Transfer release artifact to NCloud
      - name: Transfer Deploy Release jar using SCP
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.NCP_USERNAME }}
          host: ${{ secrets.NCP_HOST }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          source: "*"
          target: "~/app/backend"

      # Exec Deploy Script
      - name: Execute Server Deploy Script
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.NCP_USERNAME }}
          host: ${{ secrets.NCP_HOST }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script_stop: true
          script: chmod +x ~/app/backend && sh ~/app/backend/deploy.sh