name: unit-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        mkdir -p ./src/main/resources/secret
        echo "${{ secrets.MONGO_INFO }}" > ./src/main/resources/secret/mongo-info.yml
        echo "${{ secrets.FRONT_INFO }}" > ./src/main/resources/secret/front-info.yml
        echo "${{ secrets.SLACK_INFO }}" > ./src/main/resources/secret/slack-info.yml
        echo "${{ secrets.JWT_INFO }}" > ./src/main/resources/secret/jwt-info.yml
        echo "${{ secrets.OAUTH_INFO }}" > ./src/main/resources/secret/oauth-info.yml
    - name: Submodule Update
      run: git submodule update --init --remote
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven
    - name: build without test
      run: mvn -B package --file pom.xml
    - name: test
      run: mvn -B -Dmaven.test.failure.ignore=true test
    - name: report
      uses: dorny/test-reporter@v1
      if: success()
      with:
        name: test
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
